export {
  FLOW_SVG_ACTIVE_OVERLAY,
  FLOW_SVG_FINISHED_STROKE,
  FLOW_SVG_MUTED_STROKE,
  FLOW_SVG_PROGRESS_ARROW,
  FLOW_SVG_RUNNING_STROKE,
  FLOW_SVG_RUNTIME_DEMO_BRANCH_FILL,
  FLOW_SVG_RUNTIME_DEMO_FINISHED_FILL,
  FLOW_SVG_STROKE,
} from "@/lib/flow/svg-presentation";
